stages:
  - test
image: moreillon/tdd-dind
variables:
  REPOSITORY: "172.16.98.151:5000"
  APPLICATION_NAME: "$CI_PROJECT_NAME"
  IMAGE_NAME: "$REPOSITORY/$CI_PROJECT_NAMESPACE/$APPLICATION_NAME"

services:
  - name: docker:19.03.12-dind
    command: ["--insecure-registry=172.16.98.151:5000"]


test:
  stage: test

  script:
    - echo "$CI_JOB_STAGE"
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_COMMIT_TITLE"
    - echo "$CI_COMMIT_TAG"
    - docker build -t $IMAGE_NAME:test .
    - docker run --workdir /code --name mytest -itd $IMAGE_NAME:test
    - docker ps -a
    - docker exec mytest  bash -c "pipenv run pytest --cov"
    - docker rm -f mytest
    - docker rmi -f $IMAGE_NAME:test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  tags:
    - dind
