---
stages:
  - test
  - license

default:
  image: python:3.10

test:
  stage: test
  before_script:
    - pip install -U pip
    - pip install -U poetry
    - poetry install --with dev

  script:
    - poetry run pytest
      --cov=mediapipe_server
      --cov-report term
      --cov-report xml:coverage.xml

  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  tags:
    - dind

license:
  stage: license
  script:
    - pip install pip-licenses
    - pip-licenses --order=license
    # - pip-licenses --allow-only="MIT License;BSD License;Python Software Foundation License;Apache Software License;ISC License (ISCL);"
    - pip-licenses --summary
  tags:
    - dind
